### ISSUE TITLE
Error: value not in environment

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#326]
I thought this was caused by undo/redo, but it's in master.

Steps to reproduce:
* delete edge
* edit label for node connected to edge (node must have computed properties.)

```
ERROR Error: value not in environment
    at Environment.fromReference (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1114:1), <anonymous>:82:23) [angular]
    at util_1.deepCopy (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:569:1), <anonymous>:8:27) [angular]
    at deepCopy (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:182:1), <anonymous>:51:24) [angular]
    at Object.deepCopy (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:182:1), <anonymous>:63:23) [angular]
    at flatteningDeepCopy (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:569:1), <anonymous>:6:19) [angular]
    at fromValueInner (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:569:1), <anonymous>:46:9) [angular]
    at TypescriptPlugin.eval [as toNatural] (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:569:1), <anonymous>:187:26) [angular]
    at Object.callGetter (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1135:1), <anonymous>:53:38) [angular]
    at ElementValue.implementation (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1149:1), <anonymous>:44:27) [angular]
    at ElementValue.call (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1114:1), <anonymous>:739:69) [angular]
    at filter.forEach (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1311:1), <anonymous>:89:32) [angular]
    at Array.forEach (native) [angular]
    at ComputedPropertyContext.update (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1311:1), <anonymous>:88:100) [angular]
    at sync (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1311:1), <anonymous>:30:41) [angular]
    at Bridge.sync (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1311:1), <anonymous>:69:9) [angular]
    at Listener.Bridge.core.environment.listen [as callback] (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1311:1), <anonymous>:29:18) [angular]
    at Environment.valueChanged (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1114:1), <anonymous>:134:30) [angular]
    at Primitive.set value [as value] (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1114:1), <anonymous>:274:30) [angular]
```

**Comment by RighteousRaichu** [comment]
@Sheyne I think what's happening is that when the edge is deleted, its listener on its environment still exists and gets triggered.

There's probably a deeper issue, however, if the Environment exposed a way for me to remove listeners, I could do that before deleting the elements.

**Comment by RighteousRaichu** [comment]
@sheyne I can't reproduce, is this fixed now?

**Comment by Sheyne** [comment]
I don't know. I never saw this issue. I did change some things about core.
